name: sync_community_catalog
on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Download community catalog
        run: |
          # Download the latest community catalog and override existing one
          curl -s https://raw.githubusercontent.com/samapriya/awesome-gee-community-datasets/master/community_datasets.json -o community_datasets.json
          
          # Add timestamp file to track updates
          echo "Last updated: $(date)" > community_datasets_last_updated.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add community_datasets.json community_datasets_last_updated.txt
          git commit -m "Update community datasets catalog $(date +%Y-%m-%d)"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
